--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Inaayat04/JoinForm
build-by-default: true
branches:
- master
projects:
  JoinForm:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/FormAPI
        version: 3.1.0
    lint:
      phpstan: false
...
