---
#Join Form Configuation:
#You can use § for colours.
#. {MAX_PLAYERS} Will show the server max amount stole.
#. {ONLINE} Will show how how much player(s) is online on the server.
#. {PLAYERNAME} Will show the name of the player, Example:
#§b§lWelcome back {PLAYERNAME} /n There {ONLINE} / {MAX_PLAYERS} Online(s).
#Info: /n mean go to another line.

Form-Title: "Join Form"

#Form Message 
#Write what the news update on the server etc.

#Warning If you wanna skip or go to another line do "\n" example: Hello welcome\n to the server.
Form-Content: "Hello welcome to the server\n Enjoy you're time."

#Sumbit message.
#write what will it says when they click sumbit
Sumbit-Msg: "Thanks for reading Join Form"
...
